apiVersion: v1
kind: ConfigMap
metadata:
  name: bonding-service-config
  namespace: knowton-dev
data:
  GRPC_PORT: "50051"
  ARBITRUM_RPC_URL: "https://arb1.arbitrum.io/rpc"
  RISK_ENGINE_ENABLED: "true"
  AI_ORACLE_URL: "http://oracle-adapter:8000"
  LOG_LEVEL: "info"
---
apiVersion: v1
kind: Secret
metadata:
  name: bonding-service-secret
  namespace: knowton-dev
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/knowton?sslmode=disable"
  PRIVATE_KEY: "your_private_key_here"
  IPBOND_CONTRACT_ADDRESS: "0x0000000000000000000000000000000000000000"
  COPYRIGHT_REGISTRY_ADDRESS: "0x0000000000000000000000000000000000000000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bonding-service
  namespace: knowton-dev
  labels:
    app: bonding-service
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bonding-service
  template:
    metadata:
      labels:
        app: bonding-service
        tier: backend
    spec:
      containers:
      - name: bonding-service
        image: knowton/bonding-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: grpc
          containerPort: 50051
          protocol: TCP
        env:
        - name: GRPC_PORT
          valueFrom:
            configMapKeyRef:
              name: bonding-service-config
              key: GRPC_PORT
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: bonding-service-secret
              key: DATABASE_URL
        - name: ARBITRUM_RPC_URL
          valueFrom:
            configMapKeyRef:
              name: bonding-service-config
              key: ARBITRUM_RPC_URL
        - name: IPBOND_CONTRACT_ADDRESS
          valueFrom:
            secretKeyRef:
              name: bonding-service-secret
              key: IPBOND_CONTRACT_ADDRESS
        - name: COPYRIGHT_REGISTRY_ADDRESS
          valueFrom:
            secretKeyRef:
              name: bonding-service-secret
              key: COPYRIGHT_REGISTRY_ADDRESS
        - name: PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: bonding-service-secret
              key: PRIVATE_KEY
        - name: RISK_ENGINE_ENABLED
          valueFrom:
            configMapKeyRef:
              name: bonding-service-config
              key: RISK_ENGINE_ENABLED
        - name: AI_ORACLE_URL
          valueFrom:
            configMapKeyRef:
              name: bonding-service-config
              key: AI_ORACLE_URL
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: bonding-service-config
              key: LOG_LEVEL
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "grpc_health_probe -addr=:50051"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "grpc_health_probe -addr=:50051"
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: bonding-service
  namespace: knowton-dev
  labels:
    app: bonding-service
spec:
  type: ClusterIP
  ports:
  - port: 50051
    targetPort: 50051
    protocol: TCP
    name: grpc
  selector:
    app: bonding-service
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bonding-service-hpa
  namespace: knowton-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bonding-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
      - type: Pods
        value: 2
        periodSeconds: 30
      selectPolicy: Max
