apiVersion: apps/v1
kind: Deployment
metadata:
  name: bonding-service
  namespace: knowton-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bonding-service
  template:
    metadata:
      labels:
        app: bonding-service
    spec:
      containers:
      - name: bonding-service
        image: ghcr.io/knowton/bonding-service:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "development"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: connection-string
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        - name: ARBITRUM_RPC_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: ARBITRUM_RPC_URL
        - name: PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: wallet-secret
              key: private-key
        - name: IPBOND_CONTRACT_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: contract-addresses
              key: IPBOND_ADDRESS
        - name: COPYRIGHT_REGISTRY_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: contract-addresses
              key: COPYRIGHT_REGISTRY_ADDRESS
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: bonding-service
  namespace: knowton-dev
spec:
  selector:
    app: bonding-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bonding-service-hpa
  namespace: knowton-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bonding-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
