apiVersion: v1
kind: ConfigMap
metadata:
  name: knowton-config
  namespace: knowton-dev
data:
  NODE_ENV: "development"
  LOG_LEVEL: "debug"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "knowton"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  MONGODB_HOST: "mongodb-service"
  MONGODB_PORT: "27017"
  KAFKA_BROKERS: "kafka-service:9092"
  CLICKHOUSE_HOST: "clickhouse-service"
  CLICKHOUSE_PORT: "8123"
  ELASTICSEARCH_URL: "http://elasticsearch-service:9200"
  ARBITRUM_RPC_URL: "https://arb1.arbitrum.io/rpc"
  IPFS_GATEWAY_URL: "https://gateway.pinata.cloud"
  CORS_ORIGIN: "http://localhost:5173"
