apiVersion: v1
kind: ConfigMap
metadata:
  name: oracle-adapter-config
  namespace: knowton-dev
data:
  ENVIRONMENT: "development"
  PORT: "8000"
  HOST: "0.0.0.0"
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
  
  # IPFS Configuration
  IPFS_GATEWAY_URL: "https://gateway.pinata.cloud"
  IPFS_API_URL: "https://api.pinata.cloud"
  
  # TorchServe Configuration
  TORCHSERVE_URL: "http://torchserve:8080"
  TORCHSERVE_MANAGEMENT_URL: "http://torchserve:8081"
  
  # Vector Database
  WEAVIATE_URL: "http://weaviate:8080"
  
  # Database
  POSTGRES_URL: "postgresql://knowton:knowton@postgres:5432/knowton"
  REDIS_URL: "redis://redis:6379"
  
  # Blockchain
  ARBITRUM_RPC_URL: "https://arb1.arbitrum.io/rpc"
  
  # Model Configuration
  IMAGE_MODEL_NAME: "image_fingerprint"
  AUDIO_MODEL_NAME: "audio_fingerprint"
  VIDEO_MODEL_NAME: "video_fingerprint"
  SIMILARITY_MODEL_NAME: "similarity_detection"
  VALUATION_MODEL_NAME: "valuation_model"
  
  # Performance
  MAX_WORKERS: "4"
  BATCH_SIZE: "8"
  TIMEOUT_SECONDS: "30"

---
apiVersion: v1
kind: Secret
metadata:
  name: oracle-adapter-secret
  namespace: knowton-dev
type: Opaque
stringData:
  PINATA_API_KEY: "your-pinata-api-key"
  PINATA_SECRET_KEY: "your-pinata-secret-key"
  WEAVIATE_API_KEY: "your-weaviate-api-key"
  CHAINLINK_ORACLE_ADDRESS: "0x0000000000000000000000000000000000000000"
  AI_ORACLE_ADDRESS: "0x0000000000000000000000000000000000000000"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-adapter
  namespace: knowton-dev
  labels:
    app: oracle-adapter
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oracle-adapter
  template:
    metadata:
      labels:
        app: oracle-adapter
        tier: backend
    spec:
      containers:
      - name: oracle-adapter
        image: knowton/oracle-adapter:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        
        envFrom:
        - configMapRef:
            name: oracle-adapter-config
        - secretRef:
            name: oracle-adapter-secret
        
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        volumeMounts:
        - name: model-cache
          mountPath: /models
      
      volumes:
      - name: model-cache
        emptyDir: {}
      
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: oracle-adapter
  namespace: knowton-dev
  labels:
    app: oracle-adapter
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: oracle-adapter

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: oracle-adapter-hpa
  namespace: knowton-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: oracle-adapter
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
