apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alerts
  namespace: knowton-dev
data:
  alerts.yml: |
    groups:
      # ============================================================================
      # Service Health Alerts
      # ============================================================================
      - name: service_health
        interval: 30s
        rules:
          - alert: ServiceDown
            expr: up{job=~"knowton-.*"} == 0
            for: 2m
            labels:
              severity: critical
              category: availability
            annotations:
              summary: "Service {{ $labels.job }} is down"
              description: "Service {{ $labels.job }} has been down for more than 2 minutes."
              
          - alert: HighErrorRate
            expr: |
              (
                sum(rate(http_requests_total{job=~"knowton-.*",status=~"5.."}[5m])) by (service)
                /
                sum(rate(http_requests_total{job=~"knowton-.*"}[5m])) by (service)
              ) > 0.05
            for: 5m
            labels:
              severity: warning
              category: errors
            annotations:
              summary: "High error rate on {{ $labels.service }}"
              description: "Service {{ $labels.service }} has error rate above 5% (current: {{ $value | humanizePercentage }})."
              
          - alert: HighResponseTime
            expr: |
              histogram_quantile(0.95,
                sum(rate(http_request_duration_seconds_bucket{job=~"knowton-.*"}[5m])) by (service, le)
              ) > 1
            for: 10m
            labels:
              severity: warning
              category: performance
            annotations:
              summary: "High response time on {{ $labels.service }}"
              description: "Service {{ $labels.service }} has p95 response time above 1s (current: {{ $value }}s)."

      # ============================================================================
      # Resource Utilization Alerts
      # ============================================================================
      - name: resource_utilization
        interval: 30s
        rules:
          - alert: HighCPUUsage
            expr: |
              100 - (avg by(container) (rate(container_cpu_usage_seconds_total{namespace="knowton-dev",container!=""}[5m])) * 100) < 20
            for: 10m
            labels:
              severity: warning
              category: resources
            annotations:
              summary: "High CPU usage on {{ $labels.container }}"
              description: "Container {{ $labels.container }} has CPU usage above 80% for 10 minutes."
              
          - alert: HighMemoryUsage
            expr: |
              (container_memory_usage_bytes{namespace="knowton-dev",container!=""} 
              / 
              container_spec_memory_limit_bytes{namespace="knowton-dev",container!=""}) > 0.85
            for: 10m
            labels:
              severity: warning
              category: resources
            annotations:
              summary: "High memory usage on {{ $labels.container }}"
              description: "Container {{ $labels.container }} is using more than 85% of its memory limit."
              
          - alert: PodCrashLooping
            expr: rate(kube_pod_container_status_restarts_total{namespace="knowton-dev"}[15m]) > 0
            for: 5m
            labels:
              severity: critical
              category: stability
            annotations:
              summary: "Pod {{ $labels.pod }} is crash looping"
              description: "Pod {{ $labels.pod }} has restarted {{ $value }} times in the last 15 minutes."

      # ============================================================================
      # Database Alerts
      # ============================================================================
      - name: database_health
        interval: 30s
        rules:
          - alert: PostgreSQLDown
            expr: pg_up == 0
            for: 1m
            labels:
              severity: critical
              category: database
            annotations:
              summary: "PostgreSQL is down"
              description: "PostgreSQL database is not responding."
              
          - alert: HighDatabaseConnections
            expr: pg_stat_database_numbackends{datname="knowton"} > 80
            for: 5m
            labels:
              severity: warning
              category: database
            annotations:
              summary: "High number of PostgreSQL connections"
              description: "PostgreSQL has {{ $value }} active connections (threshold: 80)."
              
          - alert: RedisDown
            expr: redis_up == 0
            for: 1m
            labels:
              severity: critical
              category: cache
            annotations:
              summary: "Redis is down"
              description: "Redis cache is not responding."
              
          - alert: MongoDBDown
            expr: mongodb_up == 0
            for: 1m
            labels:
              severity: critical
              category: database
            annotations:
              summary: "MongoDB is down"
              description: "MongoDB database is not responding."

      # ============================================================================
      # Business Metrics Alerts
      # ============================================================================
      - name: business_metrics
        interval: 1m
        rules:
          - alert: LowNFTMintingRate
            expr: rate(knowton_nft_mints_total[1h]) < 0.001
            for: 2h
            labels:
              severity: warning
              category: business
            annotations:
              summary: "Low NFT minting rate"
              description: "NFT minting rate has been below 1 per hour for 2 hours."
              
          - alert: NoActiveUsers
            expr: knowton_active_users_total{timeframe="24h"} < 10
            for: 1h
            labels:
              severity: warning
              category: business
            annotations:
              summary: "Very low active user count"
              description: "Active users in last 24h: {{ $value }} (threshold: 10)."
              
          - alert: HighTransactionFailureRate
            expr: |
              (
                sum(rate(knowton_transaction_errors_total[5m]))
                /
                sum(rate(http_requests_total{route=~".*transaction.*"}[5m]))
              ) > 0.1
            for: 10m
            labels:
              severity: warning
              category: transactions
            annotations:
              summary: "High transaction failure rate"
              description: "Transaction failure rate is above 10% (current: {{ $value | humanizePercentage }})."
              
          - alert: LowTradingVolume
            expr: knowton_trading_volume_usd{timeframe="24h"} < 1000
            for: 6h
            labels:
              severity: info
              category: business
            annotations:
              summary: "Low trading volume"
              description: "24h trading volume is below $1000 (current: ${{ $value }})."

      # ============================================================================
      # AI Service Alerts
      # ============================================================================
      - name: ai_services
        interval: 30s
        rules:
          - alert: SlowAIProcessing
            expr: |
              histogram_quantile(0.95,
                sum(rate(knowton_ai_processing_duration_seconds_bucket[5m])) by (service, le)
              ) > 30
            for: 10m
            labels:
              severity: warning
              category: performance
            annotations:
              summary: "Slow AI processing on {{ $labels.service }}"
              description: "AI service {{ $labels.service }} has p95 processing time above 30s (current: {{ $value }}s)."
              
          - alert: HighAIErrorRate
            expr: |
              (
                sum(rate(knowton_fingerprinting_total{status="error"}[5m])) by (content_type)
                /
                sum(rate(knowton_fingerprinting_total[5m])) by (content_type)
              ) > 0.1
            for: 10m
            labels:
              severity: warning
              category: ai
            annotations:
              summary: "High AI fingerprinting error rate for {{ $labels.content_type }}"
              description: "Fingerprinting error rate for {{ $labels.content_type }} is above 10%."

      # ============================================================================
      # Blockchain Alerts
      # ============================================================================
      - name: blockchain
        interval: 1m
        rules:
          - alert: HighGasFees
            expr: avg(knowton_gas_fees_total) > 100
            for: 30m
            labels:
              severity: warning
              category: blockchain
            annotations:
              summary: "High gas fees detected"
              description: "Average gas fees are above 100 Gwei for 30 minutes."
              
          - alert: BlockchainTransactionStuck
            expr: |
              sum(increase(knowton_transaction_errors_total{error_type="timeout"}[10m])) > 5
            for: 5m
            labels:
              severity: warning
              category: blockchain
            annotations:
              summary: "Multiple blockchain transactions timing out"
              description: "{{ $value }} transactions have timed out in the last 10 minutes."

      # ============================================================================
      # Data Sync Alerts
      # ============================================================================
      - name: data_sync
        interval: 1m
        rules:
          - alert: KafkaConsumerLag
            expr: kafka_consumer_lag > 1000
            for: 10m
            labels:
              severity: warning
              category: data_sync
            annotations:
              summary: "High Kafka consumer lag"
              description: "Kafka consumer lag is above 1000 messages (current: {{ $value }})."
              
          - alert: DataSyncFailure
            expr: rate(data_sync_errors_total[5m]) > 0.1
            for: 10m
            labels:
              severity: warning
              category: data_sync
            annotations:
              summary: "Data sync failures detected"
              description: "Data sync error rate is {{ $value }} errors/sec."

      # ============================================================================
      # Security Alerts
      # ============================================================================
      - name: security
        interval: 30s
        rules:
          - alert: HighRateLimitHits
            expr: rate(rate_limit_exceeded_total[5m]) > 10
            for: 5m
            labels:
              severity: warning
              category: security
            annotations:
              summary: "High rate of rate limit violations"
              description: "Rate limit is being exceeded {{ $value }} times per second."
              
          - alert: SuspiciousAuthActivity
            expr: rate(auth_failures_total[5m]) > 5
            for: 5m
            labels:
              severity: warning
              category: security
            annotations:
              summary: "High authentication failure rate"
              description: "Authentication failures: {{ $value }} per second."
              
          - alert: UnauthorizedAccessAttempts
            expr: rate(http_requests_total{status="403"}[5m]) > 1
            for: 10m
            labels:
              severity: info
              category: security
            annotations:
              summary: "Multiple unauthorized access attempts"
              description: "Unauthorized access attempts: {{ $value }} per second."
