apiVersion: v1
kind: Secret
metadata:
  name: knowton-secrets
  namespace: knowton-dev
type: Opaque
stringData:
  # Database credentials (base64 encoded in production)
  POSTGRES_USER: "knowton"
  POSTGRES_PASSWORD: "knowton_dev_password"
  REDIS_PASSWORD: "knowton_redis_password"
  MONGODB_USER: "knowton"
  MONGODB_PASSWORD: "knowton_mongo_password"
  CLICKHOUSE_USER: "knowton"
  CLICKHOUSE_PASSWORD: "knowton_clickhouse_password"
  
  # JWT secrets
  JWT_SECRET: "dev-jwt-secret-change-in-production"
  SESSION_SECRET: "dev-session-secret-change-in-production"
  
  # Blockchain (DO NOT commit real keys)
  PRIVATE_KEY: ""
  
  # External APIs
  PINATA_API_KEY: ""
  PINATA_SECRET_KEY: ""
  ARBISCAN_API_KEY: ""
  OPENAI_API_KEY: ""
  SENTRY_DSN: ""
