---
# TraefikService for Weighted Load Balancing
apiVersion: traefik.containo.us/v1alpha1
kind: TraefikService
metadata:
  name: backend-weighted
  namespace: knowton-dev
spec:
  weighted:
    services:
      - name: backend
        port: 3000
        weight: 10
      # Add canary deployment support
      # - name: backend-canary
      #   port: 3000
      #   weight: 1

---
# TraefikService for Mirroring (Traffic Shadowing)
apiVersion: traefik.containo.us/v1alpha1
kind: TraefikService
metadata:
  name: backend-mirror
  namespace: knowton-dev
spec:
  mirroring:
    name: backend
    port: 3000
    # mirrors:
    #   - name: backend-test
    #     port: 3000
    #     percent: 10

---
# TraefikService for Sticky Sessions
apiVersion: traefik.containo.us/v1alpha1
kind: TraefikService
metadata:
  name: backend-sticky
  namespace: knowton-dev
spec:
  weighted:
    sticky:
      cookie:
        name: knowton_session
        secure: true
        httpOnly: true
        sameSite: strict
    services:
      - name: backend
        port: 3000
        weight: 10

---
# Service Discovery ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-discovery
  namespace: knowton-dev
data:
  services.yaml: |
    # Service Registry for KnowTon Platform
    services:
      backend:
        name: backend
        namespace: knowton-dev
        port: 3000
        protocol: http
        healthCheck: /health
        endpoints:
          - /api/v1/creators
          - /api/v1/content
          - /api/v1/nft
          - /api/v1/royalty
          - /api/v1/marketplace
          - /api/v1/fractional
          - /api/v1/staking
          - /api/v1/governance
          - /api/v1/lending
          - /api/v1/analytics
      
      bonding-service:
        name: bonding-service
        namespace: knowton-dev
        port: 50051
        protocol: grpc
        healthCheck: /grpc.health.v1.Health/Check
        endpoints:
          - /bonding.BondingService
      
      oracle-adapter:
        name: oracle-adapter
        namespace: knowton-dev
        port: 8000
        protocol: http
        healthCheck: /health
        endpoints:
          - /api/v1/oracle/fingerprint
          - /api/v1/oracle/similarity
          - /api/v1/oracle/valuation
          - /api/v1/oracle/recommendations
      
      frontend:
        name: frontend
        namespace: knowton-dev
        port: 80
        protocol: http
        healthCheck: /
        endpoints:
          - /

---
# HorizontalPodAutoscaler for Backend
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: knowton-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
      - type: Pods
        value: 2
        periodSeconds: 30
      selectPolicy: Max

---
# HorizontalPodAutoscaler for Traefik
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: traefik-hpa
  namespace: knowton-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: traefik
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80

---
# PodDisruptionBudget for Traefik
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: traefik-pdb
  namespace: knowton-dev
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: traefik

---
# PodDisruptionBudget for Backend
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend-pdb
  namespace: knowton-dev
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: backend
