services:
  # PostgreSQL - 主数据库
  postgres:
    image: postgres:15
    container_name: knowton-postgres
    environment:
      POSTGRES_USER: knowton
      POSTGRES_PASSWORD: knowton_dev_password
      POSTGRES_DB: knowton
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis - 缓存
  redis:
    image: redis:7-alpine
    container_name: knowton-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: