// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/bonding.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IssueBondRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IpnftId              string `protobuf:"bytes,1,opt,name=ipnft_id,json=ipnftId,proto3" json:"ipnft_id,omitempty"`
	NftContract          string `protobuf:"bytes,2,opt,name=nft_contract,json=nftContract,proto3" json:"nft_contract,omitempty"`
	TotalValue           string `protobuf:"bytes,3,opt,name=total_value,json=totalValue,proto3" json:"total_value,omitempty"`
	SeniorAllocation     string `protobuf:"bytes,4,opt,name=senior_allocation,json=seniorAllocation,proto3" json:"senior_allocation,omitempty"`
	MezzanineAllocation  string `protobuf:"bytes,5,opt,name=mezzanine_allocation,json=mezzanineAllocation,proto3" json:"mezzanine_allocation,omitempty"`
	JuniorAllocation     string `protobuf:"bytes,6,opt,name=junior_allocation,json=juniorAllocation,proto3" json:"junior_allocation,omitempty"`
	MaturityDate         int64  `protobuf:"varint,7,opt,name=maturity_date,json=maturityDate,proto3" json:"maturity_date,omitempty"`
}

func (x *IssueBondRequest) Reset() {
	*x = IssueBondRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bonding_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IssueBondRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueBondRequest) ProtoMessage() {}

func (x *IssueBondRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bonding_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *IssueBondRequest) GetIpnftId() string {
	if x != nil {
		return x.IpnftId
	}
	return ""
}

type IssueBondResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BondId string `protobuf:"bytes,1,opt,name=bond_id,json=bondId,proto3" json:"bond_id,omitempty"`
	TxHash string `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	Status string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *IssueBondResponse) Reset() {
	*x = IssueBondResponse{}
}

func (x *IssueBondResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueBondResponse) ProtoMessage() {}

func (x *IssueBondResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bonding_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var file_proto_bonding_proto_msgTypes = make([]protoimpl.MessageInfo, 2)

func init() { file_proto_bonding_proto_init() }
func file_proto_bonding_proto_init() {
	if File_proto_bonding_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_bonding_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_bonding_proto_goTypes,
		DependencyIndexes: file_proto_bonding_proto_depIdxs,
		MessageInfos:      file_proto_bonding_proto_msgTypes,
	}.Build()
	File_proto_bonding_proto = out.File
	file_proto_bonding_proto_rawDesc = nil
	file_proto_bonding_proto_goTypes = nil
	file_proto_bonding_proto_depIdxs = nil
}

var (
	file_proto_bonding_proto_rawDesc = []byte{}
	file_proto_bonding_proto_goTypes = []interface{}{}
	file_proto_bonding_proto_depIdxs = []int32{}
	File_proto_bonding_proto protoreflect.FileDescriptor
)
